_target_: src.models.multilabel_classification_module.MultiLabelClassificationModule
loss: "bce"
backbone: "spec_resnet50"
learning_rate: 1e-3
weight_decay: 1e-5
pretrained_weights: null
in_channels: ${data.num_bands}
num_classes: 19
freeze_backbone: False
eta_min: 0
t_max: 100