_target_: src.models.semantic_segmentation_module.SemanticSegmentationModule
seg_model: "conv_head"
backbone: "spec_vit_small"
pretrained_weights: null
in_channels: ${data.num_bands}
num_classes: null
ignore_index: null
learning_rate: 1e-3
weight_decay: 1e-4
eta_min: 0
t_max: 100
freeze_backbone: False