# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# you can replace it with "." if you want the root to be the current working directory
root_dir: "."

# path to data directory
data_dir: "/dss/dsstbyfs02/pn49cu/pn49cu-dss-0001/enmap_data_final/spectral_earth"
#"path/to/spectral_earth/"


# path to logging directory
log_dir: logs/

# path to pretrained models
weights_dir: pretrained_weights/

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}


#hpdar01c04s01